first_name = input ("Please enter your first name? ")
surname = input ("Please enter your surname? ")
age = input ("What is your age? ")
height = input ("What is your height in cm? ")
print(f"{height}cm")
student = input ("Are you a student? True or False ")

first_name = str(first_name)
surname = str(surname)
age = int(age)
height = int(height)
student = bool(student)
